config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places, except: [:update, :edit, :destroy]
  root 'places#index'

  resources :distances, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
 attr_accessor :raw_address

  geocoded_by :raw_address
  reverse_geocoded_by :latitude, :longitude

  after_validation -> {
    self.address = self.raw_address
    geocode
  }, if: ->(obj){ obj.raw_address.present? and obj.raw_address != obj.address }

  after_validation :reverse_geocode, unless: ->(obj) { obj.raw_address.present? },
                   if: ->(obj){ obj.latitude.present? and obj.latitude_changed? and obj.longitude.present? and obj.longitude_changed? }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/distances_controller.rb
class DistancesController < ApplicationController
  def new
    @places = Place.all
  end

  def create
    @from = Place.find_by(id: params[:from])
    @to = Place.find_by(id: params[:to])
    if @from && @to
      flash[:success] =
          "The distance between <b>#{@from.title}</b> and <b>#{@to.title}</b> is #{@from.distance_from(@to.to_coordinates)} km"
    end
    redirect_to new_distance_path
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    if params[:search].present?
      @places = Place.near(params[:search], 10, :order => :distance)
    else
      @places = Place.all
    end
  end

  def new
    @place = Place.new
  end

  def show
  @place = Place.find(params[:id])
  end
  
  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:success] = "Place added!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def place_params
    params.require(:place).permit(:title, :raw_address, :latitude, :longitude, :visited_by)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/distances_helper.rb
module DistancesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/distances/new.html.erb
<header><h1 class="display-4">Measure Distance</h1></header>

<%= form_tag distances_path do %>
  <fieldset class="form-group">
  	<%= label_tag 'from', 'From' %>
  	<%= select_tag 'from', options_from_collection_for_select(@places, :id, :title), class: "form-control" %>
	</fieldset>

  <fieldset class="form-group">
  	<%= label_tag 'to', 'To' %>
  	<%= select_tag 'to', options_from_collection_for_select(@places, :id, :title), class: "form-control" %>
	</fieldset>

  <%= submit_tag 'Go!', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Location</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDV9e6yk84jLPVviXJfTlM1034Z3wF3YD8&callback=initMap"
                                         async defer></script>
  </head>

  <body>
    <nav class="navbar navbar-inverse bg-inverse">
      <%= link_to 'Location', root_path, class: 'navbar-brand' %>

      <ul class="nav navbar-nav">
        <li class="nav-item">
          <%= link_to 'Places', places_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Place', new_place_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Measure distance between places', new_distance_path, class: 'nav-link' %>
        </li>
      </ul>
    </nav>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg.html_safe, class: "alert alert-#{name}") %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
  <fieldset class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :raw_address, 'Address' %>
    <%= f.text_field :raw_address, class: "form-control" %>
    <small class="text-muted">You can also enter IP. Your IP is <%= request.ip %></small>
  </fieldset>

  <div class="form-group row">
    <div class="col-sm-1">
      <%= f.label :latitude %>
    </div>

    <div class="col-sm-3">
      <%= f.text_field :latitude, class: "form-control" %>
    </div>

      <div class="col-sm-1">
        <%= f.label :longitude %>
      </div>

      <div class="col-sm-3">
        <%= f.text_field :longitude, class: "form-control" %>
      </div>

      <div class="col-sm-4">
        <a href="#" id="find-on-map" class="btn btn-info btn-sm">Find on map</a>
      </div>
  </div>

  <%= f.submit 'Add Place', class: 'btn btn-primary' %>
<% end %>

<div class="card">
  <div class="card-block">
    <div id="map"></div>
  </div>
</div>

app/views/places/_place.html.erb
<li>
  <%= link_to place.title, place_path(place) %>
</li>

app/views/places/index.html.erb
<header><h1 class="display-4">Places</h1></header>

<%= link_to 'Add place', new_place_path, class: 'btn btn-primary btn-lg' %>
<%= form_tag places_path, :method => :get do %>
  <p>
    <%#= text_field_tag :search, params[:search] %>
    <%#= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<div class="card">
  <div class="card-block">
    <ul>
     <% for place in @places %>
     
      <% end %>
       <%= render @places %>
    </ul>
  </div>
</div>

app/views/places/new.html.erb
<header><h1 class="display-4">Add Place</h1></header>

<%= render 'form' %>

app/views/places/show.html.erb
<header><h1 class="display-4"><%= @place.title %></h1></header>

<p>Address: <%= @place.address %></p>
<p>Coordinates: <%= @place.latitude %> <%= @place.longitude %></p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@place.latitude}%2C#{@place.longitude}" %>
 <h3>Nearby locations</h3>
<ul>
<% for place in @place.nearbys(3) %>
  <li><%= link_to place.address, place %> (<%= place.distance.round()/0.7 %> km)</li>
<% end %>
</ul>